"""recipes."""

from loguru import logger

__version__ = '0.0.1'
__pkg_name__ = 'recipes'

logger.disable(__pkg_name__)

# =============== Above is Auto-Generated by calcipy. User content goes below ===============
