# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.0.4
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
copyright_date: '2021'
package_name_py: recipes
project_description: Recipe Website
project_name: recipes
repository_namespace: kyleking
repository_provider: https://github.com
