version: 0.2.0.{build}

image:
  # Recipes isn't a package. Only need to run on Ubuntu for CD
  - Ubuntu

environment:
  # Windows Python versions: https://www.appveyor.com/docs/windows-images-software/#python
  #   For linux: https://www.appveyor.com/docs/linux-images-software/#python
  matrix:
    # Nox will handle python version testing. This only sets the global environment for pipx/poetry/etc.
    - PYTHON_WIN: C:/Python39
      PYTHON_STACK: 3.9

  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  CODECOV_TOKEN: d414dacb-5b8d-4c0b-94e1-42fe8393187d

  # To encrypt passwords, in the AppVeyor Account, go to "Settings" -> "Encrypt YAML"
  GH_ACCESS_TOKEN:
    secure: dw5Lg976wGTiU48NTSPb+fG4nUm287ACpZu6egFc92J5KUAcEYweUzL9vUgHEdE6

# See: https://help.appveyor.com/discussions/questions/32001-ubuntu-python-3-as-default
stack: python %PYTHON_STACK%

cache:
  - .venv -> poetry.lock

build: off

# Specify commands specific to platform (cmd-Windows/sh-Linux/None-Both)
install:
# Set Python paths based on environment variable from matrix
- cmd: set PATH=%PYTHON_WIN%/Scripts;%PYTHON_WIN%;%PATH%
- python --version
# Install pipx to manage CLI installations (poetry, codecov)
- python -m pip install pipx
# Set the path to the pipx bin because "python -m pipx ensurepath" doesn't work without reload
- cmd: set PATH=%USERPROFILE%\.local\bin;%PATH%
- sh: PATH=~/.local/bin:$PATH
# Debug the PATH (if needed)
- cmd: echo %PATH%
- sh: echo $PATH
# Install poetry and configure
- python -m pipx install poetry
- poetry config --list
- poetry config virtualenvs.in-project true
# Install project-specific dependencies and extras
- poetry install

test_script:
- poetry run doit run main coverage

deploy_script:
- echo "Deploying..."
# See: https://www.appveyor.com/docs/how-to/git-push/
- sh: git config --global user.name "Kyle King"
- sh: git config --global user.email "dev.act.kyle@gmail.com"
- sh: git config --global credential.helper store
- sh: echo -e "https://$GH_ACCESS_TOKEN:x-oauth-basic@github.com\n" >> ~/.git-credentials
- sh: poetry run doit run deploy

on_success:
- echo "On Success..."
# Install codecov and upload the coverage results
- python -m pipx install codecov
- codecov

on_failure:
- echo "On Error..."

artifacts:
  # PLANNED: Specify single files, like wheels, but zip the docs/reports
  - path: releases/tests/*
