---
site_name: recipes
site_author: Kyle King and Alexandra Gabitzer
site_description: Kyle and Alex's Personal Recipes
site_url: https://recipes.kyleking.me
repo_name: kyleking/recipes
repo_url: https://github.com/kyleking/recipes
# Note: modified for top-level docs/ directory
edit_uri: edit/main/docs
docs_dir: docs
site_dir: releases/site

theme:
  name: material
  custom_dir: docs/_theme
  palette:
    - scheme: default
      primary: white
      accent: green
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.autohide

watch:
  - recipes

plugins:
  - build_plantuml:
      render: server # or "local"
      bin_path: /usr/local/bin/plantuml # ignored when render: server
      server: http://www.plantuml.com/plantuml # official plantuml server
      output_format: svg
      diagram_root: docs/diagrams
      output_folder: out
      input_folder: src
      input_extensions: puml
  # # Don't generate code documentation
  # - gen-files:
  #     scripts:
  #       - docs-code/gen_ref_nav.py
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      strict: false
      type: date
  # # Don't generate code documentation
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_section_style: spacy
  #           line_length: 120
  #           separate_signature: true
  #           show_category_heading: true
  - search
  - section-index
  - live-edit

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - def_list
  - extra
  - fenced_code
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - smarty
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 0

extra_css:
  - _styles/mkdocstrings.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _javascript/tables.js
