site_name: Recipes
site_author: Kyle King and Alexandra Gabitzer
site_description: Kyle and Alex's Personal Recipes
repo_name: kyleking/recipes
repo_url: https://github.com/kyleking/recipes
edit_uri: edit/main/docs/z_dev
docs_dir: docs/z_dev
site_dir: releases/site

theme:
  name: material
  custom_dir: docs/_theme
  palette:
    - scheme: default
      primary: white
      accent: green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - toc.autohide

plugins:
  - search
  - git-revision-date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - extra
  - fenced_code
  - footnotes
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - smarty
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 3

extra:
  manifest: manifest.webmanifest

extra_css:
  - _stylesheets/extra.css

extra_javascript:
  - _javascript/hider.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _javascript/tables.js
