site_name: Recipes
site_author: Kyle King and Alexandra Gabitzer
site_description: Kyle and Alex's Personal Recipes
repo_name: KyleKing/recipes
repo_url: https://github.com/KyleKing/recipes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - toc.autohide

plugins:
  - search
  - git-revision-date

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3

extra:
  manifest: manifest.webmanifest

extra_css:
  - _stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _javascript/tables.js
