#!/bin/bash
# Setup script for go-spacy C++ wrapper library
# Writes environment configuration to .env for mise to load
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$PROJECT_ROOT/lib"
BUILD_DIR="/tmp/go-spacy-build"
ENV_FILE="$PROJECT_ROOT/.env"

echo "Setting up go-spacy C++ wrapper..."

# Verify spacy is installed
if ! python3 -c "import spacy" 2>/dev/null; then
    echo "ERROR: spacy is not installed in the current Python environment"
    echo "Install with: pip install spacy"
    exit 1
fi

# Verify model is installed
if ! python3 -c "import spacy; spacy.load('en_core_web_sm')" 2>/dev/null; then
    echo "ERROR: en_core_web_sm model is not installed"
    echo "Install with: python -m spacy download en_core_web_sm"
    exit 1
fi

echo "Python: $(which python3)"
echo "spacy version: $(python3 -c 'import spacy; print(spacy.__version__)')"

# Get Python library path
PYTHON_LIB_PATH=$(python3-config --prefix)/lib

# Detect OS and set extension
if [[ "$OSTYPE" == "darwin"* ]]; then
    SHARED_EXT="dylib"
    LIB_PATH_VAR="DYLD_LIBRARY_PATH"
else
    SHARED_EXT="so"
    LIB_PATH_VAR="LD_LIBRARY_PATH"
fi

# Create lib directory
mkdir -p "$LIB_DIR"

# Write environment configuration to .env
write_env_file() {
    echo "Writing environment configuration to .env..."
    cat > "$ENV_FILE" << EOF
# Auto-generated by setup-spacy.sh
# Do not edit manually - re-run ./setup-spacy.sh to regenerate
CGO_LDFLAGS=-L$LIB_DIR -L$PYTHON_LIB_PATH -Wl,-rpath,$LIB_DIR -Wl,-rpath,$PYTHON_LIB_PATH
$LIB_PATH_VAR=$LIB_DIR:$PYTHON_LIB_PATH
EOF
    echo "Environment written to $ENV_FILE"
}

# Check if library already exists
if [ -f "$LIB_DIR/libspacy_wrapper.$SHARED_EXT" ]; then
    echo "go-spacy library already exists"
    write_env_file
    exit 0
fi

# Copy go-spacy source to temp directory
echo "Copying go-spacy source..."
go mod download github.com/am-sokolov/go-spacy
GOSPACY_PATH=$(go list -m -f '{{.Dir}}' github.com/am-sokolov/go-spacy)
if [ -z "$GOSPACY_PATH" ] || [ ! -d "$GOSPACY_PATH" ]; then
    echo "ERROR: Could not find go-spacy module directory"
    echo "GOSPACY_PATH='$GOSPACY_PATH'"
    exit 1
fi
echo "go-spacy source: $GOSPACY_PATH"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cp -rL "$GOSPACY_PATH"/* "$BUILD_DIR/" 2>/dev/null || cp -R "$GOSPACY_PATH"/* "$BUILD_DIR/"
chmod -R u+w "$BUILD_DIR"

# Build the C++ wrapper
echo "Building C++ wrapper..."
cd "$BUILD_DIR"

# Create build directories
mkdir -p build lib

# Compile
echo "Compiling..."

# Get Python include path using sysconfig (more reliable than python3-config)
PYTHON_INCLUDE=$(python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')
echo "Python include directory: $PYTHON_INCLUDE"

# Verify Python.h exists
if [ ! -f "$PYTHON_INCLUDE/Python.h" ]; then
    echo "ERROR: Python.h not found at $PYTHON_INCLUDE/Python.h"
    echo "Contents of $PYTHON_INCLUDE:"
    ls -la "$PYTHON_INCLUDE" 2>&1 || echo "Directory does not exist"
    exit 1
fi

# Try python3-config first, fall back to manual flags
if PYTHON_CFLAGS=$(python3-config --cflags 2>/dev/null); then
    echo "Using python3-config --cflags: $PYTHON_CFLAGS"
else
    echo "python3-config not available, using sysconfig"
    PYTHON_CFLAGS="-I$PYTHON_INCLUDE"
fi

echo "Full compile command:"
echo "c++ -Wall -Wextra -fPIC -std=c++17 -Iinclude -O3 -DNDEBUG $PYTHON_CFLAGS -c cpp/spacy_wrapper.cpp -o build/spacy_wrapper.o"
c++ -Wall -Wextra -fPIC -std=c++17 -Iinclude -O3 -DNDEBUG \
    $PYTHON_CFLAGS \
    -c cpp/spacy_wrapper.cpp -o build/spacy_wrapper.o

# Link
echo "Linking..."
if [[ "$OSTYPE" == "darwin"* ]]; then
    c++ -shared -install_name @rpath/libspacy_wrapper.dylib \
        -o lib/libspacy_wrapper.$SHARED_EXT \
        build/spacy_wrapper.o \
        -L"$PYTHON_LIB_PATH" \
        "$(python3-config --ldflags)"
else
    c++ -shared -Wl,-soname,libspacy_wrapper.$SHARED_EXT \
        -o lib/libspacy_wrapper.$SHARED_EXT \
        build/spacy_wrapper.o \
        -L"$PYTHON_LIB_PATH" \
        "$(python3-config --ldflags)"
fi

# Copy to project lib directory
echo "Installing library..."
cp lib/libspacy_wrapper.$SHARED_EXT "$LIB_DIR/"

echo "go-spacy library installed to $LIB_DIR"

# Write environment file
write_env_file
