#!/bin/bash
# Setup script for go-spacy C++ wrapper library
# Writes environment configuration to .env for mise to load
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$PROJECT_ROOT/lib"
BUILD_DIR="/tmp/go-spacy-build"
ENV_FILE="$PROJECT_ROOT/.env"

echo "Setting up go-spacy C++ wrapper..."

# Verify spacy is installed
if ! python3 -c "import spacy" 2>/dev/null; then
    echo "ERROR: spacy is not installed in the current Python environment"
    echo "Install with: pip install spacy"
    exit 1
fi

# Verify model is installed
if ! python3 -c "import spacy; spacy.load('en_core_web_sm')" 2>/dev/null; then
    echo "ERROR: en_core_web_sm model is not installed"
    echo "Install with: python -m spacy download en_core_web_sm"
    exit 1
fi

echo "Python: $(which python3)"
echo "spacy version: $(python3 -c 'import spacy; print(spacy.__version__)')"

# Get Python library path and embed flags
PYTHON_LIB_PATH=$(python3-config --prefix)/lib
# Get Python embed library name (e.g., python3.13) for linking - use version info as most reliable source
PYTHON_EMBED_LIB=$(python3 -c "import sys; print(f'python{sys.version_info.major}.{sys.version_info.minor}')")
echo "Python library path: $PYTHON_LIB_PATH"
echo "Python embed library: $PYTHON_EMBED_LIB"

# Verify the Python library exists
if [ ! -f "$PYTHON_LIB_PATH/lib${PYTHON_EMBED_LIB}.so" ] && [ ! -f "$PYTHON_LIB_PATH/lib${PYTHON_EMBED_LIB}.dylib" ] && [ ! -f "$PYTHON_LIB_PATH/lib${PYTHON_EMBED_LIB}.a" ]; then
    echo "WARNING: Python library not found at expected path, checking alternative locations..."
    # Try the config directory path
    PYTHON_CONFIG_LIB_PATH=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
    if [ -n "$PYTHON_CONFIG_LIB_PATH" ] && [ -d "$PYTHON_CONFIG_LIB_PATH" ]; then
        echo "Using alternative library path: $PYTHON_CONFIG_LIB_PATH"
        PYTHON_LIB_PATH="$PYTHON_CONFIG_LIB_PATH"
    fi
fi

# Detect OS and set extension
if [[ "$OSTYPE" == "darwin"* ]]; then
    SHARED_EXT="dylib"
    LIB_PATH_VAR="DYLD_LIBRARY_PATH"
else
    SHARED_EXT="so"
    LIB_PATH_VAR="LD_LIBRARY_PATH"
fi

# Create lib directory
mkdir -p "$LIB_DIR"

# Get go-spacy module path (needed for copying library later)
echo "Finding go-spacy module..."
go mod download github.com/am-sokolov/go-spacy
GOSPACY_PATH=$(go list -m -f '{{.Dir}}' github.com/am-sokolov/go-spacy)
if [ -z "$GOSPACY_PATH" ] || [ ! -d "$GOSPACY_PATH" ]; then
    echo "ERROR: Could not find go-spacy module directory"
    echo "GOSPACY_PATH='$GOSPACY_PATH'"
    exit 1
fi
echo "go-spacy source: $GOSPACY_PATH"

# Write environment configuration to .env
write_env_file() {
    echo "Writing environment configuration to .env..."
    # Note: Quoted values work for local shell sourcing and mise will handle them correctly
    # For GitHub Actions, we'll use a custom loading script that strips quotes
    cat > "$ENV_FILE" << EOF
# Auto-generated by setup-spacy.sh
# Do not edit manually - re-run ./setup-spacy.sh to regenerate
export CGO_LDFLAGS="-L$LIB_DIR -L$PYTHON_LIB_PATH -l$PYTHON_EMBED_LIB -Wl,-rpath,$LIB_DIR -Wl,-rpath,$PYTHON_LIB_PATH"
export $LIB_PATH_VAR="$LIB_DIR:$PYTHON_LIB_PATH"
EOF
    echo "Environment written to $ENV_FILE"
    echo "Environment variables set:"
    cat "$ENV_FILE" | grep -v '^#' | grep -v '^$'
}

# Copy library to go-spacy module lib directory (if writable)
copy_to_gospacy_lib() {
    echo "Attempting to copy library to go-spacy module lib directory..."
    if mkdir -p "$GOSPACY_PATH/lib" 2>/dev/null && [ -w "$GOSPACY_PATH/lib" ]; then
        cp "$LIB_DIR/libspacy_wrapper.$SHARED_EXT" "$GOSPACY_PATH/lib/"
        echo "Library copied to $GOSPACY_PATH/lib/"
    else
        echo "Note: go-spacy module lib directory is not writable (this is normal for go module cache)"
        echo "Library will be found via CGO_LDFLAGS instead"
    fi
}

# Verify library exists and is valid
verify_library() {
    if [ ! -f "$LIB_DIR/libspacy_wrapper.$SHARED_EXT" ]; then
        echo "ERROR: Library file not found at $LIB_DIR/libspacy_wrapper.$SHARED_EXT"
        return 1
    fi

    # Check if library is readable and non-empty
    if [ ! -r "$LIB_DIR/libspacy_wrapper.$SHARED_EXT" ] || [ ! -s "$LIB_DIR/libspacy_wrapper.$SHARED_EXT" ]; then
        echo "ERROR: Library file exists but is not readable or is empty"
        return 1
    fi

    echo "Library verified: $LIB_DIR/libspacy_wrapper.$SHARED_EXT"
    ls -lh "$LIB_DIR/libspacy_wrapper.$SHARED_EXT"
    return 0
}

# Check if library already exists and is valid
if verify_library 2>/dev/null; then
    echo "go-spacy library already exists and is valid"
    copy_to_gospacy_lib
    write_env_file
    exit 0
fi

echo "go-spacy library not found or invalid, building from source..."

# Copy go-spacy source to temp directory
echo "Copying go-spacy source..."
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cp -rL "$GOSPACY_PATH"/* "$BUILD_DIR/" 2>/dev/null || cp -R "$GOSPACY_PATH"/* "$BUILD_DIR/"
chmod -R u+w "$BUILD_DIR"

# Build the C++ wrapper
echo "Building C++ wrapper..."
cd "$BUILD_DIR"

# Create build directories
mkdir -p build lib

# Compile
echo "Compiling..."

# Get Python include path using sysconfig (more reliable than python3-config)
PYTHON_INCLUDE=$(python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')
echo "Python include directory: $PYTHON_INCLUDE"

# Verify Python.h exists
if [ ! -f "$PYTHON_INCLUDE/Python.h" ]; then
    echo "ERROR: Python.h not found at $PYTHON_INCLUDE/Python.h"
    echo "Contents of $PYTHON_INCLUDE:"
    ls -la "$PYTHON_INCLUDE" 2>&1 || echo "Directory does not exist"
    exit 1
fi

# Try python3-config first, fall back to manual flags
if PYTHON_CFLAGS=$(python3-config --cflags 2>/dev/null); then
    echo "Using python3-config --cflags: $PYTHON_CFLAGS"
else
    echo "python3-config not available, using sysconfig"
    PYTHON_CFLAGS="-I$PYTHON_INCLUDE"
fi

echo "Full compile command:"
echo "c++ -Wall -Wextra -fPIC -std=c++17 -Iinclude -O3 -DNDEBUG $PYTHON_CFLAGS -c cpp/spacy_wrapper.cpp -o build/spacy_wrapper.o"
c++ -Wall -Wextra -fPIC -std=c++17 -Iinclude -O3 -DNDEBUG \
    $PYTHON_CFLAGS \
    -c cpp/spacy_wrapper.cpp -o build/spacy_wrapper.o

# Link
echo "Linking..."
PYTHON_LDFLAGS=$(python3-config --ldflags)
echo "Python ldflags: $PYTHON_LDFLAGS"

if [[ "$OSTYPE" == "darwin"* ]]; then
    c++ -shared -install_name @rpath/libspacy_wrapper.dylib \
        -o lib/libspacy_wrapper.$SHARED_EXT \
        build/spacy_wrapper.o \
        -L"$PYTHON_LIB_PATH" \
        $PYTHON_LDFLAGS
else
    c++ -shared -Wl,-soname,libspacy_wrapper.$SHARED_EXT \
        -o lib/libspacy_wrapper.$SHARED_EXT \
        build/spacy_wrapper.o \
        -L"$PYTHON_LIB_PATH" \
        $PYTHON_LDFLAGS
fi

# Copy to project lib directory
echo "Installing library..."
cp lib/libspacy_wrapper.$SHARED_EXT "$LIB_DIR/"

echo "go-spacy library installed to $LIB_DIR"

# Copy to go-spacy module lib directory
copy_to_gospacy_lib

# Write environment file
write_env_file
