---
name: CI Pipeline

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - recipes/**
      - tests/**
      - pyproject.toml

env:
  COLUMNS: 120

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Run static linters
        run: ./run lint.check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Run test
        run: poetry run calcipy test.pytest

  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Run typecheck
        run: ./run types.mypy

      # TODO: Resolve why the virtual environment isn't found
      # - uses: jakebailey/pyright-action@v1
