---
# Docs: https://github.com/marketplace/actions/github-labeler

name: github_labeler

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  workflow_dispatch:  # For manual runs

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
