---
name: Update Docs

"on":
  push:
    branches: [main]
    paths:
      - .github/workflows/update_docs.yml
      - docs/**
      - build.sh
  workflow_dispatch: null # For manual runs

# Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

# From: https://steveasleep.com/djockey/guides/deploying.html
#   Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
#   However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true # required for go backend

      # https://github.com/mkdocs/mkdocs/discussions/2369#discussioncomment-625475
      - name: Configure git user
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build Site
        run: ./build.sh

      - name: Deploy
        run: ./push-gh-pages.sh
