---
name: Update Docs

"on":
  push:
    branches: [main]
    paths:
      - .github/workflows/update_docs.yml
      - docs/**
      - build.sh
  workflow_dispatch: null # For manual runs

# Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      # https://github.com/mkdocs/mkdocs/discussions/2369#discussioncomment-625475
      - name: Configure git user
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build Site
        run: ./build.sh

      - name: Deploy
        run: |-
          git checkout --orphan gh-pages
          git reset .
          cp -r public .
          git add .
          git status
          git commit --message="build"
          git push -u origin gh-pages --force
