---
name: Update Docs

"on":
  push:
    branches: [main]
    paths:
      - .github/workflows/update_docs.yml
      - docs/**
      - build.sh
  workflow_dispatch: null # For manual runs

# Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
      - run: go install github.com/tdewolff/minify/v2/cmd/minify@latest

      - uses: actions/setup-node@v4
      - run: npm ci

      # https://github.com/mkdocs/mkdocs/discussions/2369#discussioncomment-625475
      - name: Configure git user
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build Site
        run: ./build.sh

      - name: Deploy
        run: ./push-gh-pages.sh
